### ISSUE TITLE
For Shared Hosting

### ISSUE THREAD

**Issue by thesrivastava** [DavidWittman/csrgenerator.com#23]
Not a Techie...

If I need to install it on my Linux Shared Hosting on a Sub Domain how will I do the same.

Thanks

**Comment by DavidWittman** [comment]
@thesrivastava Does your shared hosting support Docker or Python installations? You can also use the public version at https://csrgenerator.com if that works for you.

**Comment by thesrivastava** [comment]
It's does support python but not on hosting plan I have.

Anyway I was hoping it was easy as like installation of WP.  Ex One Click
Install.

Regard
Abhishek Srivastava

**Comment by DavidWittman** [comment]
I'm afraid not. The closest thing would be running it in Docker, which is documented on the README:

https://github.com/DavidWittman/csrgenerator.com#running-with-docker

Best of luck.

**Comment by thesrivastava** [comment]
Aaa

I am looking something less techi based.

Anyway Thanks & Luck to you.

Regards
Abhishek
