### ISSUE TITLE
Support SAN domains

### ISSUE THREAD

**Issue by DavidWittman** [DavidWittman/csrgenerator.com#27]
Most modern TLS implementations rely on the Subject Alternative Names instead of the CN anyway.

**Comment by onedropsync** [comment]
@DavidWittman : when can the SAN filed implementation will be done on csrgenerator.com.
Looking forward to it.

As you stated many TLS implementations rely on the Subject Alternative Names.

**Comment by 0x86f** [comment]
Hi David,

i noticed you didn't continue working on this issue. After having a look at the branch, i thought there is just a short snippet needed in the `index.html` below the `div` for the CN. 

It could be (simply) something like this:
```html
<div class="form-group">
    <label class="form-label tooltip tooltip-left" data-tooltip="Comma separated list of alternative names" for="CN">Alternative Names</label>
    <input class="form-input input-lg" type="text" placeholder="*.example.com, *.another.example.com" name="subjectAltNames" />
</div>
```

I tried it myself and it looks like it's working:
```
.............
        Attributes:
        Requested Extensions:
            X509v3 Subject Alternative Name:
                DNS:*.example.com, DNS:*.another.example.com, DNS:example.com
.............
```

Regards,
Felix

**Comment by StrikeZW** [comment]
Thats fine for the html,
but the returned SANhas to be placed or piped into the csr generation

i.e.: 
san_list = ["IP:" + common_name, "DNS:" + common_name]
req.add_extensions([
    OpenSSL.crypto.X509Extension(
        "subjectAltName".encode("utf-8"), False, (", ".join(san_list)).encode("utf-8")
    )

i am currently working on adding this to csr.py to get this done

**Comment by elange** [comment]
> Thats fine for the html, but the returned SANhas to be placed or piped into the csr generation
> 
> i.e.: san_list = ["IP:" + common_name, "DNS:" + common_name] req.add_extensions([ OpenSSL.crypto.X509Extension( "subjectAltName".encode("utf-8"), False, (", ".join(san_list)).encode("utf-8") )
> 
> i am currently working on adding this to csr.py to get this done

@StrikeZW did you ever get this done?

**Comment by 0x86f** [comment]
Hi there,

on the python-side i rewrote Davids code at https://github.com/DavidWittman/csrgenerator.com/blob/27-subject-alt-names/csr.py#L99-L105 a bit:

```python
if self.csr_info.get('sans'):
     # commonName should be at first position
     sans = ['DNS:{}'.format(self.csr_info['CN'])]
     for entry in self.csr_info['sans']:
         # CN was already added, so skip it
         if entry['name'] != self.csr_info['CN']:
             sans.append('{}:{}'.format(entry['network'].upper(), entry['name']))

        sans = str.encode(', '.join(sans))
        type_name = str.encode('subjectAltName')

        x509_san = crypt.X509Extension(type_name, False, sans)
        request.add_extensions([x509_san])
```

Hope that helps you guys.

Regards,
Felix

**Comment by 0x86f** [comment]
Hi @AlexBarth13,

checkout the code from the branch [27-subject-alt-names](https://github.com/DavidWittman/csrgenerator.com/tree/27-subject-alt-names) and add the few lines (index.html and csr.py) i already written about (see above). You will get a version, which solves the issue.

Regards,
Felix

**Comment by JamesM-NC** [comment]
Any update on when/if this will be compiled into the main version?

**Comment by DavidWittman** [comment]
@JamesM-NC this is now in the master branch and has been deployed to https://csrgenerator.com -- let me know if you have any issues!
