### ISSUE TITLE
Use HTML5 "placeholder" attribute instead of jQuery-Watermark

### ISSUE THREAD

**Issue by n-st** [DavidWittman/csrgenerator.com#9]
Since you're using HTML5 anyway, you might as well replace the ugly hack that is [jQuery-Watermark](https://github.com/marioestrada/jQuery-Watermark) with the new [`placeholder` attribute](http://www.w3schools.com/tags/att_input_placeholder.asp) introduced with HTML5. ;)

**Comment by DavidWittman** [comment]
I take "ugly hack" as a term of endearment. :) Good point though, I forget why I originally went with jQuery Watermark over `placeholder`, but I'll re-evaluate this now.
